server:
  port: 8093
spring:
  application:
    name: notification-service
  cloud:
    config:
      uri: http://localhost:8888
      profile: native
    stream:
      bindings:
        input:
          destination: delivery

  rabbitmq:
    username: admin
    password: root
