sp:
  cassandra:
    datacenter: datacenter1
    keyspace:
      name: spcloud
    port: '9042'
    contact-point: localhost
    passw: cassandra.
    uname: cassandra.
spring:
  application:
    name: account-service
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost