spring:
  application:
    name: delivery-service
  datasource:
    username: root
    password: admin
    url: jdbc:mysql://localhost:3306/deliverydb

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
eureka:
  client:
    serviceUrl:
      defaultZone : http://localhost:8761/eureka
  instance:
    hostname: localhost
