spring:
  application:
    name: notification-service
  cloud:
    stream:
      bindings:
        input:
          destination: delivery

  rabbitmq:
    username: admin
    password: root

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost