version: '3.1'
services:
  cassandra:
    image: cassandra
    ports:
      - "9042:9042"
  mongo:
    image: mongo
    ports:
      - "27017:27017"

    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: root
